[package]
name = "media_player"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1", features = ["full"]}
axum = "0.8.4"
tower-http  = { version = "0.6.2", features = ["fs"] }
urlencoding = "2.1.3"
local-ip-address = "0.6.2"

[dev-dependencies]
anyhow = "1"